<?php
function file_type($ext, $name = false) {
    switch($ext) {
    case ".x3d": return ($name) ? "3D Crossword Plugin" : "application/vnd.hzn-3d-crossword";
    case ".3gp": return ($name) ? "3GP" : "video/3gpp";
    case ".3g2": return ($name) ? "3GP2" : "video/3gpp2";
    case ".mseq": return ($name) ? "3GPP MSEQ File" : "application/vnd.mseq";
    case ".pwn": return ($name) ? "3M Post It Notes" : "application/vnd.3m.post-it-notes";
    case ".plb": return ($name) ? "3rd Generation Partnership Project - Pic Large" : "application/vnd.3gpp.pic-bw-large";
    case ".psb": return ($name) ? "3rd Generation Partnership Project - Pic Small" : "application/vnd.3gpp.pic-bw-small";
    case ".pvb": return ($name) ? "3rd Generation Partnership Project - Pic Var" : "application/vnd.3gpp.pic-bw-var";
    case ".tcap": return ($name) ? "3rd Generation Partnership Project - Transaction Capabilities Application Part" : "application/vnd.3gpp2.tcap";
    case ".7z": return ($name) ? "7-Zip" : "application/x-7z-compressed";
    case ".abw": return ($name) ? "AbiWord" : "application/x-abiword";
    case ".ace": return ($name) ? "Ace Archive" : "application/x-ace-compressed";
    case ".acc": return ($name) ? "Active Content Compression" : "application/vnd.americandynamics.acc";
    case ".acu": return ($name) ? "ACU Cobol" : "application/vnd.acucobol";
    case ".atc": return ($name) ? "ACU Cobol" : "application/vnd.acucorp";
    case ".adp": return ($name) ? "Adaptive differential pulse-code modulation" : "audio/adpcm";
    case ".aab": return ($name) ? "Adobe (Macropedia) Authorware - Binary File" : "application/x-authorware-bin";
    case ".aam": return ($name) ? "Adobe (Macropedia) Authorware - Map" : "application/x-authorware-map";
    case ".aas": return ($name) ? "Adobe (Macropedia) Authorware - Segment File" : "application/x-authorware-seg";
    case ".air": return ($name) ? "Adobe AIR Application" : "application/vnd.adobe.air-application-installer-package+zip";
    case ".swf": return ($name) ? "Adobe Flash" : "application/x-shockwave-flash";
    case ".fxp": return ($name) ? "Adobe Flex Project" : "application/vnd.adobe.fxp";
    case ".pdf": return ($name) ? "Adobe Portable Document Format" : "application/pdf";
    case ".ppd": return ($name) ? "Adobe PostScript Printer Description File Format" : "application/vnd.cups-ppd";
    case ".dir": return ($name) ? "Adobe Shockwave Player" : "application/x-director";
    case ".xdp": return ($name) ? "Adobe XML Data Package" : "application/vnd.adobe.xdp+xml";
    case ".xfdf": return ($name) ? "Adobe XML Forms Data Format" : "application/vnd.adobe.xfdf";
    case ".aac": return ($name) ? "Advanced Audio Coding (AAC)" : "audio/x-aac";
    case ".ahead": return ($name) ? "Ahead AIR Application" : "application/vnd.ahead.space";
    case ".azf": return ($name) ? "AirZip FileSECURE" : "application/vnd.airzip.filesecure.azf";
    case ".azs": return ($name) ? "AirZip FileSECURE" : "application/vnd.airzip.filesecure.azs";
    case ".azw": return ($name) ? "Amazon Kindle eBook format" : "application/vnd.amazon.ebook";
    case ".ami": return ($name) ? "AmigaDE" : "application/vnd.amiga.ami";
    case "N/A": return ($name) ? "Andrew Toolkit" : "application/andrew-inset";
    case ".apk": return ($name) ? "Android Package Archive" : "application/vnd.android.package-archive";
    case ".cii": return ($name) ? "ANSER-WEB Terminal Client - Certificate Issue" : "application/vnd.anser-web-certificate-issue-initiation";
    case ".fti": return ($name) ? "ANSER-WEB Terminal Client - Web Funds Transfer" : "application/vnd.anser-web-funds-transfer-initiation";
    case ".atx": return ($name) ? "Antix Game Player" : "application/vnd.antix.game-component";
    case ".mpkg": return ($name) ? "Apple Installer Package" : "application/vnd.apple.installer+xml";
    case ".aw": return ($name) ? "Applixware" : "application/applixware";
    case ".les": return ($name) ? "Archipelago Lesson Player" : "application/vnd.hhe.lesson-player";
    case ".swi": return ($name) ? "Arista Networks Software Image" : "application/vnd.aristanetworks.swi";
    case ".s": return ($name) ? "Assembler Source File" : "text/x-asm";
    case ".atomcat": return ($name) ? "Atom Publishing Protocol" : "application/atomcat+xml";
    case ".atomsvc": return ($name) ? "Atom Publishing Protocol Service Document" : "application/atomsvc+xml";
    case ".atom, .xml": return ($name) ? "Atom Syndication Format" : "application/atom+xml";
    case ".ac": return ($name) ? "Attribute Certificate" : "application/pkix-attr-cert";
    case ".aif": return ($name) ? "Audio Interchange File Format" : "audio/x-aiff";
    case ".avi": return ($name) ? "Audio Video Interleave (AVI)" : "video/x-msvideo";
    case ".aep": return ($name) ? "Audiograph" : "application/vnd.audiograph";
    case ".dxf": return ($name) ? "AutoCAD DXF" : "image/vnd.dxf";
    case ".dwf": return ($name) ? "Autodesk Design Web Format (DWF)" : "model/vnd.dwf";
    case ".par": return ($name) ? "BAS Partitur Format" : "text/plain-bas";
    case ".bcpio": return ($name) ? "Binary CPIO Archive" : "application/x-bcpio";
    case ".bin": return ($name) ? "Binary Data" : "application/octet-stream";
    case ".bmp": return ($name) ? "Bitmap Image File" : "image/bmp";
    case ".torrent": return ($name) ? "BitTorrent" : "application/x-bittorrent";
    case ".cod": return ($name) ? "Blackberry COD File" : "application/vnd.rim.cod";
    case ".mpm": return ($name) ? "Blueice Research Multipass" : "application/vnd.blueice.multipass";
    case ".bmi": return ($name) ? "BMI Drawing Data Interchange" : "application/vnd.bmi";
    case ".sh": return ($name) ? "Bourne Shell Script" : "application/x-sh";
    case ".btif": return ($name) ? "BTIF" : "image/prs.btif";
    case ".rep": return ($name) ? "BusinessObjects" : "application/vnd.businessobjects";
    case ".bz": return ($name) ? "Bzip Archive" : "application/x-bzip";
    case ".bz2": return ($name) ? "Bzip2 Archive" : "application/x-bzip2";
    case ".csh": return ($name) ? "C Shell Script" : "application/x-csh";
    case ".c": return ($name) ? "C Source File" : "text/x-c";
    case ".cdxml": return ($name) ? "CambridgeSoft Chem Draw" : "application/vnd.chemdraw+xml";
    case ".css": return ($name) ? "Cascading Style Sheets (CSS)" : "text/css";
    case ".cdx": return ($name) ? "ChemDraw eXchange file" : "chemical/x-cdx";
    case ".cml": return ($name) ? "Chemical Markup Language" : "chemical/x-cml";
    case ".csml": return ($name) ? "Chemical Style Markup Language" : "chemical/x-csml";
    case ".cdbcmsg": return ($name) ? "CIM Database" : "application/vnd.contact.cmsg";
    case ".cla": return ($name) ? "Claymore Data Files" : "application/vnd.claymore";
    case ".c4g": return ($name) ? "Clonk Game" : "application/vnd.clonk.c4group";
    case ".sub": return ($name) ? "Close Captioning - Subtitle" : "image/vnd.dvb.subtitle";
    case ".cdmia": return ($name) ? "Cloud Data Management Interface (CDMI) - Capability" : "application/cdmi-capability";
    case ".cdmic": return ($name) ? "Cloud Data Management Interface (CDMI) - Contaimer" : "application/cdmi-container";
    case ".cdmid": return ($name) ? "Cloud Data Management Interface (CDMI) - Domain" : "application/cdmi-domain";
    case ".cdmio": return ($name) ? "Cloud Data Management Interface (CDMI) - Object" : "application/cdmi-object";
    case ".cdmiq": return ($name) ? "Cloud Data Management Interface (CDMI) - Queue" : "application/cdmi-queue";
    case ".c11amc": return ($name) ? "ClueTrust CartoMobile - Config" : "application/vnd.cluetrust.cartomobile-config";
    case ".c11amz": return ($name) ? "ClueTrust CartoMobile - Config Package" : "application/vnd.cluetrust.cartomobile-config-pkg";
    case ".ras": return ($name) ? "CMU Image" : "image/x-cmu-raster";
    case ".dae": return ($name) ? "COLLADA" : "model/vnd.collada+xml";
    case ".csv": return ($name) ? "Comma-Seperated Values" : "text/csv";
    case ".cpt": return ($name) ? "Compact Pro" : "application/mac-compactpro";
    case ".wmlc": return ($name) ? "Compiled Wireless Markup Language (WMLC)" : "application/vnd.wap.wmlc";
    case ".cgm": return ($name) ? "Computer Graphics Metafile" : "image/cgm";
    case ".ice": return ($name) ? "CoolTalk" : "x-conference/x-cooltalk";
    case ".cmx": return ($name) ? "Corel Metafile Exchange (CMX)" : "image/x-cmx";
    case ".xar": return ($name) ? "CorelXARA" : "application/vnd.xara";
    case ".cmc": return ($name) ? "CosmoCaller" : "application/vnd.cosmocaller";
    case ".cpio": return ($name) ? "CPIO Archive" : "application/x-cpio";
    case ".clkx": return ($name) ? "CrickSoftware - Clicker" : "application/vnd.crick.clicker";
    case ".clkk": return ($name) ? "CrickSoftware - Clicker - Keyboard" : "application/vnd.crick.clicker.keyboard";
    case ".clkp": return ($name) ? "CrickSoftware - Clicker - Palette" : "application/vnd.crick.clicker.palette";
    case ".clkt": return ($name) ? "CrickSoftware - Clicker - Template" : "application/vnd.crick.clicker.template";
    case ".clkw": return ($name) ? "CrickSoftware - Clicker - Wordbank" : "application/vnd.crick.clicker.wordbank";
    case ".wbs": return ($name) ? "Critical Tools - PERT Chart EXPERT" : "application/vnd.criticaltools.wbs+xml";
    case ".cryptonote": return ($name) ? "CryptoNote" : "application/vnd.rig.cryptonote";
    case ".cif": return ($name) ? "Crystallographic Interchange Format" : "chemical/x-cif";
    case ".cmdf": return ($name) ? "CrystalMaker Data Format" : "chemical/x-cmdf";
    case ".cu": return ($name) ? "CU-SeeMe" : "application/cu-seeme";
    case ".cww": return ($name) ? "CU-Writer" : "application/prs.cww";
    case ".curl": return ($name) ? "Curl - Applet" : "text/vnd.curl";
    case ".dcurl": return ($name) ? "Curl - Detached Applet" : "text/vnd.curl.dcurl";
    case ".mcurl": return ($name) ? "Curl - Manifest File" : "text/vnd.curl.mcurl";
    case ".scurl": return ($name) ? "Curl - Source Code" : "text/vnd.curl.scurl";
    case ".car": return ($name) ? "CURL Applet" : "application/vnd.curl.car";
    case ".pcurl": return ($name) ? "CURL Applet" : "application/vnd.curl.pcurl";
    case ".cmp": return ($name) ? "CustomMenu" : "application/vnd.yellowriver-custom-menu";
    case ".dssc": return ($name) ? "Data Structure for the Security Suitability of Cryptographic Algorithms" : "application/dssc+der";
    case ".xdssc": return ($name) ? "Data Structure for the Security Suitability of Cryptographic Algorithms" : "application/dssc+xml";
    case ".deb": return ($name) ? "Debian Package" : "application/x-debian-package";
    case ".uva": return ($name) ? "DECE Audio" : "audio/vnd.dece.audio";
    case ".uvi": return ($name) ? "DECE Graphic" : "image/vnd.dece.graphic";
    case ".uvh": return ($name) ? "DECE High Definition Video" : "video/vnd.dece.hd";
    case ".uvm": return ($name) ? "DECE Mobile Video" : "video/vnd.dece.mobile";
    case ".uvu": return ($name) ? "DECE MP4" : "video/vnd.uvvu.mp4";
    case ".uvp": return ($name) ? "DECE PD Video" : "video/vnd.dece.pd";
    case ".uvs": return ($name) ? "DECE SD Video" : "video/vnd.dece.sd";
    case ".uvv": return ($name) ? "DECE Video" : "video/vnd.dece.video";
    case ".dvi": return ($name) ? "Device Independent File Format (DVI)" : "application/x-dvi";
    case ".seed": return ($name) ? "Digital Siesmograph Networks - SEED Datafiles" : "application/vnd.fdsn.seed";
    case ".dtb": return ($name) ? "Digital Talking Book" : "application/x-dtbook+xml";
    case ".res": return ($name) ? "Digital Talking Book - Resource File" : "application/x-dtbresource+xml";
    case ".ait": return ($name) ? "Digital Video Broadcasting" : "application/vnd.dvb.ait";
    case ".svc": return ($name) ? "Digital Video Broadcasting" : "application/vnd.dvb.service";
    case ".eol": return ($name) ? "Digital Winds Music" : "audio/vnd.digital-winds";
    case ".djvu": return ($name) ? "DjVu" : "image/vnd.djvu";
    case ".dtd": return ($name) ? "Document Type Definition" : "application/xml-dtd";
    case ".mlp": return ($name) ? "Dolby Meridian Lossless Packing" : "application/vnd.dolby.mlp";
    case ".wad": return ($name) ? "Doom Video Game" : "application/x-doom";
    case ".dpg": return ($name) ? "DPGraph" : "application/vnd.dpgraph";
    case ".dra": return ($name) ? "DRA Audio" : "audio/vnd.dra";
    case ".dfac": return ($name) ? "DreamFactory" : "application/vnd.dreamfactory";
    case ".dts": return ($name) ? "DTS Audio" : "audio/vnd.dts";
    case ".dtshd": return ($name) ? "DTS High Definition Audio" : "audio/vnd.dts.hd";
    case ".dwg": return ($name) ? "DWG Drawing" : "image/vnd.dwg";
    case ".geo": return ($name) ? "DynaGeo" : "application/vnd.dynageo";
    case ".es": return ($name) ? "ECMAScript" : "application/ecmascript";
    case ".mag": return ($name) ? "EcoWin Chart" : "application/vnd.ecowin.chart";
    case ".mmr": return ($name) ? "EDMICS 2000" : "image/vnd.fujixerox.edmics-mmr";
    case ".rlc": return ($name) ? "EDMICS 2000" : "image/vnd.fujixerox.edmics-rlc";
    case ".exi": return ($name) ? "Efficient XML Interchange" : "application/exi";
    case ".mgz": return ($name) ? "EFI Proteus" : "application/vnd.proteus.magazine";
    case ".epub": return ($name) ? "Electronic Publication" : "application/epub+zip";
    case ".eml": return ($name) ? "Email Message" : "message/rfc822";
    case ".nml": return ($name) ? "Enliven Viewer" : "application/vnd.enliven";
    case ".xpr": return ($name) ? "Express by Infoseek" : "application/vnd.is-xpr";
    case ".xif": return ($name) ? "eXtended Image File Format (XIFF)" : "image/vnd.xiff";
    case ".xfdl": return ($name) ? "Extensible Forms Description Language" : "application/vnd.xfdl";
    case ".emma": return ($name) ? "Extensible MultiModal Annotation" : "application/emma+xml";
    case ".ez2": return ($name) ? "EZPix Secure Photo Album" : "application/vnd.ezpix-album";
    case ".ez3": return ($name) ? "EZPix Secure Photo Album" : "application/vnd.ezpix-package";
    case ".fst": return ($name) ? "FAST Search & Transfer ASA" : "image/vnd.fst";
    case ".fvt": return ($name) ? "FAST Search & Transfer ASA" : "video/vnd.fvt";
    case ".fbs": return ($name) ? "FastBid Sheet" : "image/vnd.fastbidsheet";
    case ".fe_launch": return ($name) ? "FCS Express Layout Link" : "application/vnd.denovo.fcselayout-link";
    case ".f4v": return ($name) ? "Flash Video" : "video/x-f4v";
    case ".flv": return ($name) ? "Flash Video" : "video/x-flv";
    case ".fpx": return ($name) ? "FlashPix" : "image/vnd.fpx";
    case ".npx": return ($name) ? "FlashPix" : "image/vnd.net-fpx";
    case ".flx": return ($name) ? "FLEXSTOR" : "text/vnd.fmi.flexstor";
    case ".fli": return ($name) ? "FLI/FLC Animation Format" : "video/x-fli";
    case ".ftc": return ($name) ? "FluxTime Clip" : "application/vnd.fluxtime.clip";
    case ".fdf": return ($name) ? "Forms Data Format" : "application/vnd.fdf";
    case ".f": return ($name) ? "Fortran Source File" : "text/x-fortran";
    case ".mif": return ($name) ? "FrameMaker Interchange Format" : "application/vnd.mif";
    case ".fm": return ($name) ? "FrameMaker Normal Format" : "application/vnd.framemaker";
    case ".fh": return ($name) ? "FreeHand MX" : "image/x-freehand";
    case ".fsc": return ($name) ? "Friendly Software Corporation" : "application/vnd.fsc.weblaunch";
    case ".fnc": return ($name) ? "Frogans Player" : "application/vnd.frogans.fnc";
    case ".ltf": return ($name) ? "Frogans Player" : "application/vnd.frogans.ltf";
    case ".ddd": return ($name) ? "Fujitsu - Xerox 2D CAD Data" : "application/vnd.fujixerox.ddd";
    case ".xdw": return ($name) ? "Fujitsu - Xerox DocuWorks" : "application/vnd.fujixerox.docuworks";
    case ".xbd": return ($name) ? "Fujitsu - Xerox DocuWorks Binder" : "application/vnd.fujixerox.docuworks.binder";
    case ".oas": return ($name) ? "Fujitsu Oasys" : "application/vnd.fujitsu.oasys";
    case ".oa2": return ($name) ? "Fujitsu Oasys" : "application/vnd.fujitsu.oasys2";
    case ".oa3": return ($name) ? "Fujitsu Oasys" : "application/vnd.fujitsu.oasys3";
    case ".fg5": return ($name) ? "Fujitsu Oasys" : "application/vnd.fujitsu.oasysgp";
    case ".bh2": return ($name) ? "Fujitsu Oasys" : "application/vnd.fujitsu.oasysprs";
    case ".spl": return ($name) ? "FutureSplash Animator" : "application/x-futuresplash";
    case ".fzs": return ($name) ? "FuzzySheet" : "application/vnd.fuzzysheet";
    case ".g3": return ($name) ? "G3 Fax Image" : "image/g3fax";
    case ".gmx": return ($name) ? "GameMaker ActiveX" : "application/vnd.gmx";
    case ".gtw": return ($name) ? "Gen-Trix Studio" : "model/vnd.gtw";
    case ".txd": return ($name) ? "Genomatix Tuxedo Framework" : "application/vnd.genomatix.tuxedo";
    case ".ggb": return ($name) ? "GeoGebra" : "application/vnd.geogebra.file";
    case ".ggt": return ($name) ? "GeoGebra" : "application/vnd.geogebra.tool";
    case ".gdl": return ($name) ? "Geometric Description Language (GDL)" : "model/vnd.gdl";
    case ".gex": return ($name) ? "GeoMetry Explorer" : "application/vnd.geometry-explorer";
    case ".gxt": return ($name) ? "GEONExT and JSXGraph" : "application/vnd.geonext";
    case ".g2w": return ($name) ? "GeoplanW" : "application/vnd.geoplan";
    case ".g3w": return ($name) ? "GeospacW" : "application/vnd.geospace";
    case ".gsf": return ($name) ? "Ghostscript Font" : "application/x-font-ghostscript";
    case ".bdf": return ($name) ? "Glyph Bitmap Distribution Format" : "application/x-font-bdf";
    case ".gtar": return ($name) ? "GNU Tar Files" : "application/x-gtar";
    case ".texinfo": return ($name) ? "GNU Texinfo Document" : "application/x-texinfo";
    case ".gnumeric": return ($name) ? "Gnumeric" : "application/x-gnumeric";
    case ".kml": return ($name) ? "Google Earth - KML" : "application/vnd.google-earth.kml+xml";
    case ".kmz": return ($name) ? "Google Earth - Zipped KML" : "application/vnd.google-earth.kmz";
    case ".gqf": return ($name) ? "GrafEq" : "application/vnd.grafeq";
    case ".gif": return ($name) ? "Graphics Interchange Format" : "image/gif";
    case ".gv": return ($name) ? "Graphviz" : "text/vnd.graphviz";
    case ".gac": return ($name) ? "Groove - Account" : "application/vnd.groove-account";
    case ".ghf": return ($name) ? "Groove - Help" : "application/vnd.groove-help";
    case ".gim": return ($name) ? "Groove - Identity Message" : "application/vnd.groove-identity-message";
    case ".grv": return ($name) ? "Groove - Injector" : "application/vnd.groove-injector";
    case ".gtm": return ($name) ? "Groove - Tool Message" : "application/vnd.groove-tool-message";
    case ".tpl": return ($name) ? "Groove - Tool Template" : "application/vnd.groove-tool-template";
    case ".vcg": return ($name) ? "Groove - Vcard" : "application/vnd.groove-vcard";
    case ".h261": return ($name) ? "H.261" : "video/h261";
    case ".h263": return ($name) ? "H.263" : "video/h263";
    case ".h264": return ($name) ? "H.264" : "video/h264";
    case ".hpid": return ($name) ? "Hewlett Packard Instant Delivery" : "application/vnd.hp-hpid";
    case ".hps": return ($name) ? "Hewlett-Packard's WebPrintSmart" : "application/vnd.hp-hps";
    case ".hdf": return ($name) ? "Hierarchical Data Format" : "application/x-hdf";
    case ".rip": return ($name) ? "Hit'n'Mix" : "audio/vnd.rip";
    case ".hbci": return ($name) ? "Homebanking Computer Interface (HBCI)" : "application/vnd.hbci";
    case ".jlt": return ($name) ? "HP Indigo Digital Press - Job Layout Languate" : "application/vnd.hp-jlyt";
    case ".pcl": return ($name) ? "HP Printer Command Language" : "application/vnd.hp-pcl";
    case ".hpgl": return ($name) ? "HP-GL/2 and HP RTL" : "application/vnd.hp-hpgl";
    case ".hvs": return ($name) ? "HV Script" : "application/vnd.yamaha.hv-script";
    case ".hvd": return ($name) ? "HV Voice Dictionary" : "application/vnd.yamaha.hv-dic";
    case ".hvp": return ($name) ? "HV Voice Parameter" : "application/vnd.yamaha.hv-voice";
    case ".sfd-hdstx": return ($name) ? "Hydrostatix Master Suite" : "application/vnd.hydrostatix.sof-data";
    case ".stk": return ($name) ? "Hyperstudio" : "application/hyperstudio";
    case ".hal": return ($name) ? "Hypertext Application Language" : "application/vnd.hal+xml";
    case ".html": return ($name) ? "HyperText Markup Language (HTML)" : "text/html";
    case ".irm": return ($name) ? "IBM DB2 Rights Manager" : "application/vnd.ibm.rights-management";
    case ".sc": return ($name) ? "IBM Electronic Media Management System - Secure Container" : "application/vnd.ibm.secure-container";
    case ".ics": return ($name) ? "iCalendar" : "text/calendar";
    case ".icc": return ($name) ? "ICC profile" : "application/vnd.iccprofile";
    case ".ico": return ($name) ? "Icon Image" : "image/x-icon";
    case ".igl": return ($name) ? "igLoader" : "application/vnd.igloader";
    case ".ief": return ($name) ? "Image Exchange Format" : "image/ief";
    case ".ivp": return ($name) ? "ImmerVision PURE Players" : "application/vnd.immervision-ivp";
    case ".ivu": return ($name) ? "ImmerVision PURE Players" : "application/vnd.immervision-ivu";
    case ".rif": return ($name) ? "IMS Networks" : "application/reginfo+xml";
    case ".3dml": return ($name) ? "In3D - 3DML" : "text/vnd.in3d.3dml";
    case ".spot": return ($name) ? "In3D - 3DML" : "text/vnd.in3d.spot";
    case ".igs": return ($name) ? "Initial Graphics Exchange Specification (IGES)" : "model/iges";
    case ".i2g": return ($name) ? "Interactive Geometry Software" : "application/vnd.intergeo";
    case ".cdy": return ($name) ? "Interactive Geometry Software Cinderella" : "application/vnd.cinderella";
    case ".xpw": return ($name) ? "Intercon FormNet" : "application/vnd.intercon.formnet";
    case ".fcs": return ($name) ? "International Society for Advancement of Cytometry" : "application/vnd.isac.fcs";
    case ".ipfix": return ($name) ? "Internet Protocol Flow Information Export" : "application/ipfix";
    case ".cer": return ($name) ? "Internet Public Key Infrastructure - Certificate" : "application/pkix-cert";
    case ".pki": return ($name) ? "Internet Public Key Infrastructure - Certificate Management Protocole" : "application/pkixcmp";
    case ".crl": return ($name) ? "Internet Public Key Infrastructure - Certificate Revocation Lists" : "application/pkix-crl";
    case ".pkipath": return ($name) ? "Internet Public Key Infrastructure - Certification Path" : "application/pkix-pkipath";
    case ".igm": return ($name) ? "IOCOM Visimeet" : "application/vnd.insors.igm";
    case ".rcprofile": return ($name) ? "IP Unplugged Roaming Client" : "application/vnd.ipunplugged.rcprofile";
    case ".irp": return ($name) ? "iRepository / Lucidoc Editor" : "application/vnd.irepository.package+xml";
    case ".jad": return ($name) ? "J2ME App Descriptor" : "text/vnd.sun.j2me.app-descriptor";
    case ".jar": return ($name) ? "Java Archive" : "application/java-archive";
    case ".class": return ($name) ? "Java Bytecode File" : "application/java-vm";
    case ".jnlp": return ($name) ? "Java Network Launching Protocol" : "application/x-java-jnlp-file";
    case ".ser": return ($name) ? "Java Serialized Object" : "application/java-serialized-object";
    case ".java": return ($name) ? "Java Source File" : "text/x-java-source,java";
    case ".js": return ($name) ? "JavaScript" : "application/javascript";
    case ".json": return ($name) ? "JavaScript Object Notation (JSON)" : "application/json";
    case ".joda": return ($name) ? "Joda Archive" : "application/vnd.joost.joda-archive";
    case ".jpm": return ($name) ? "JPEG 2000 Compound Image File Format" : "video/jpm";
    case ".jpeg, .jpg": return ($name) ? "JPEG Image" : "image/jpeg";
    case ".jpgv": return ($name) ? "JPGVideo" : "video/jpeg";
    case ".ktz": return ($name) ? "Kahootz" : "application/vnd.kahootz";
    case ".mmd": return ($name) ? "Karaoke on Chipnuts Chipsets" : "application/vnd.chipnuts.karaoke-mmd";
    case ".karbon": return ($name) ? "KDE KOffice Office Suite - Karbon" : "application/vnd.kde.karbon";
    case ".chrt": return ($name) ? "KDE KOffice Office Suite - KChart" : "application/vnd.kde.kchart";
    case ".kfo": return ($name) ? "KDE KOffice Office Suite - Kformula" : "application/vnd.kde.kformula";
    case ".flw": return ($name) ? "KDE KOffice Office Suite - Kivio" : "application/vnd.kde.kivio";
    case ".kon": return ($name) ? "KDE KOffice Office Suite - Kontour" : "application/vnd.kde.kontour";
    case ".kpr": return ($name) ? "KDE KOffice Office Suite - Kpresenter" : "application/vnd.kde.kpresenter";
    case ".ksp": return ($name) ? "KDE KOffice Office Suite - Kspread" : "application/vnd.kde.kspread";
    case ".kwd": return ($name) ? "KDE KOffice Office Suite - Kword" : "application/vnd.kde.kword";
    case ".htke": return ($name) ? "Kenamea App" : "application/vnd.kenameaapp";
    case ".kia": return ($name) ? "Kidspiration" : "application/vnd.kidspiration";
    case ".kne": return ($name) ? "Kinar Applications" : "application/vnd.kinar";
    case ".sse": return ($name) ? "Kodak Storyshare" : "application/vnd.kodak-descriptor";
    case ".lasxml": return ($name) ? "Laser App Enterprise" : "application/vnd.las.las+xml";
    case ".latex": return ($name) ? "LaTeX" : "application/x-latex";
    case ".lbd": return ($name) ? "Life Balance - Desktop Edition" : "application/vnd.llamagraphics.life-balance.desktop";
    case ".lbe": return ($name) ? "Life Balance - Exchange Format" : "application/vnd.llamagraphics.life-balance.exchange+xml";
    case ".jam": return ($name) ? "Lightspeed Audio Lab" : "application/vnd.jam";
    case ".123": return ($name) ? "Lotus 1-2-3" : "application/vnd.lotus-1-2-3";
    case ".apr": return ($name) ? "Lotus Approach" : "application/vnd.lotus-approach";
    case ".pre": return ($name) ? "Lotus Freelance" : "application/vnd.lotus-freelance";
    case ".nsf": return ($name) ? "Lotus Notes" : "application/vnd.lotus-notes";
    case ".org": return ($name) ? "Lotus Organizer" : "application/vnd.lotus-organizer";
    case ".scm": return ($name) ? "Lotus Screencam" : "application/vnd.lotus-screencam";
    case ".lwp": return ($name) ? "Lotus Wordpro" : "application/vnd.lotus-wordpro";
    case ".lvp": return ($name) ? "Lucent Voice" : "audio/vnd.lucent.voice";
    case ".m3u": return ($name) ? "M3U (Multimedia Playlist)" : "audio/x-mpegurl";
    case ".m4v": return ($name) ? "M4v" : "video/x-m4v";
    case ".hqx": return ($name) ? "Macintosh BinHex 4.0" : "application/mac-binhex40";
    case ".portpkg": return ($name) ? "MacPorts Port System" : "application/vnd.macports.portpkg";
    case ".mgp": return ($name) ? "MapGuide DBXML" : "application/vnd.osgeo.mapguide.package";
    case ".mrc": return ($name) ? "MARC Formats" : "application/marc";
    case ".mrcx": return ($name) ? "MARC21 XML Schema" : "application/marcxml+xml";
    case ".mxf": return ($name) ? "Material Exchange Format" : "application/mxf";
    case ".nbp": return ($name) ? "Mathematica Notebook Player" : "application/vnd.wolfram.player";
    case ".ma": return ($name) ? "Mathematica Notebooks" : "application/mathematica";
    case ".mathml": return ($name) ? "Mathematical Markup Language" : "application/mathml+xml";
    case ".mbox": return ($name) ? "Mbox database files" : "application/mbox";
    case ".mc1": return ($name) ? "MedCalc" : "application/vnd.medcalcdata";
    case ".mscml": return ($name) ? "Media Server Control Markup Language" : "application/mediaservercontrol+xml";
    case ".cdkey": return ($name) ? "MediaRemote" : "application/vnd.mediastation.cdkey";
    case ".mwf": return ($name) ? "Medical Waveform Encoding Format" : "application/vnd.mfer";
    case ".mfm": return ($name) ? "Melody Format for Mobile Platform" : "application/vnd.mfmp";
    case ".msh": return ($name) ? "Mesh Data Type" : "model/mesh";
    case ".mads": return ($name) ? "Metadata Authority Description Schema" : "application/mads+xml";
    case ".mets": return ($name) ? "Metadata Encoding and Transmission Standard" : "application/mets+xml";
    case ".mods": return ($name) ? "Metadata Object Description Schema" : "application/mods+xml";
    case ".meta4": return ($name) ? "Metalink" : "application/metalink4+xml";
    case ".potm": return ($name) ? "Micosoft PowerPoint - Macro-Enabled Template File" : "application/vnd.ms-powerpoint.template.macroenabled.12";
    case ".docm": return ($name) ? "Micosoft Word - Macro-Enabled Document" : "application/vnd.ms-word.document.macroenabled.12";
    case ".dotm": return ($name) ? "Micosoft Word - Macro-Enabled Template" : "application/vnd.ms-word.template.macroenabled.12";
    case ".mcd": return ($name) ? "Micro CADAM Helix D&D" : "application/vnd.mcd";
    case ".flo": return ($name) ? "Micrografx" : "application/vnd.micrografx.flo";
    case ".igx": return ($name) ? "Micrografx iGrafx Professional" : "application/vnd.micrografx.igx";
    case ".es3": return ($name) ? "MICROSEC e-Szign¢" : "application/vnd.eszigno3+xml";
    case ".mdb": return ($name) ? "Microsoft Access" : "application/x-msaccess";
    case ".asf": return ($name) ? "Microsoft Advanced Systems Format (ASF)" : "video/x-ms-asf";
    case ".exe": return ($name) ? "Microsoft Application" : "application/x-msdownload";
    case ".cil": return ($name) ? "Microsoft Artgalry" : "application/vnd.ms-artgalry";
    case ".cab": return ($name) ? "Microsoft Cabinet File" : "application/vnd.ms-cab-compressed";
    case ".ims": return ($name) ? "Microsoft Class Server" : "application/vnd.ms-ims";
    case ".application": return ($name) ? "Microsoft ClickOnce" : "application/x-ms-application";
    case ".clp": return ($name) ? "Microsoft Clipboard Clip" : "application/x-msclip";
    case ".mdi": return ($name) ? "Microsoft Document Imaging Format" : "image/vnd.ms-modi";
    case ".eot": return ($name) ? "Microsoft Embedded OpenType" : "application/vnd.ms-fontobject";
    case ".xls": return ($name) ? "Microsoft Excel" : "application/vnd.ms-excel";
    case ".xlam": return ($name) ? "Microsoft Excel - Add-In File" : "application/vnd.ms-excel.addin.macroenabled.12";
    case ".xlsb": return ($name) ? "Microsoft Excel - Binary Workbook" : "application/vnd.ms-excel.sheet.binary.macroenabled.12";
    case ".xltm": return ($name) ? "Microsoft Excel - Macro-Enabled Template File" : "application/vnd.ms-excel.template.macroenabled.12";
    case ".xlsm": return ($name) ? "Microsoft Excel - Macro-Enabled Workbook" : "application/vnd.ms-excel.sheet.macroenabled.12";
    case ".chm": return ($name) ? "Microsoft Html Help File" : "application/vnd.ms-htmlhelp";
    case ".crd": return ($name) ? "Microsoft Information Card" : "application/x-mscardfile";
    case ".lrm": return ($name) ? "Microsoft Learning Resource Module" : "application/vnd.ms-lrm";
    case ".mvb": return ($name) ? "Microsoft MediaView" : "application/x-msmediaview";
    case ".mny": return ($name) ? "Microsoft Money" : "application/x-msmoney";
    case ".pptx": return ($name) ? "Microsoft Office - OOXML - Presentation" : "application/vnd.openxmlformats-officedocument.presentationml.presentation";
    case ".sldx": return ($name) ? "Microsoft Office - OOXML - Presentation (Slide)" : "application/vnd.openxmlformats-officedocument.presentationml.slide";
    case ".ppsx": return ($name) ? "Microsoft Office - OOXML - Presentation (Slideshow)" : "application/vnd.openxmlformats-officedocument.presentationml.slideshow";
    case ".potx": return ($name) ? "Microsoft Office - OOXML - Presentation Template" : "application/vnd.openxmlformats-officedocument.presentationml.template";
    case ".xlsx": return ($name) ? "Microsoft Office - OOXML - Spreadsheet" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    case ".xltx": return ($name) ? "Microsoft Office - OOXML - Spreadsheet Teplate" : "application/vnd.openxmlformats-officedocument.spreadsheetml.template";
    case ".docx": return ($name) ? "Microsoft Office - OOXML - Word Document" : "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    case ".dotx": return ($name) ? "Microsoft Office - OOXML - Word Document Template" : "application/vnd.openxmlformats-officedocument.wordprocessingml.template";
    case ".obd": return ($name) ? "Microsoft Office Binder" : "application/x-msbinder";
    case ".thmx": return ($name) ? "Microsoft Office System Release Theme" : "application/vnd.ms-officetheme";
    case ".onetoc": return ($name) ? "Microsoft OneNote" : "application/onenote";
    case ".pya": return ($name) ? "Microsoft PlayReady Ecosystem" : "audio/vnd.ms-playready.media.pya";
    case ".pyv": return ($name) ? "Microsoft PlayReady Ecosystem Video" : "video/vnd.ms-playready.media.pyv";
    case ".ppt": return ($name) ? "Microsoft PowerPoint" : "application/vnd.ms-powerpoint";
    case ".ppam": return ($name) ? "Microsoft PowerPoint - Add-in file" : "application/vnd.ms-powerpoint.addin.macroenabled.12";
    case ".sldm": return ($name) ? "Microsoft PowerPoint - Macro-Enabled Open XML Slide" : "application/vnd.ms-powerpoint.slide.macroenabled.12";
    case ".pptm": return ($name) ? "Microsoft PowerPoint - Macro-Enabled Presentation File" : "application/vnd.ms-powerpoint.presentation.macroenabled.12";
    case ".ppsm": return ($name) ? "Microsoft PowerPoint - Macro-Enabled Slide Show File" : "application/vnd.ms-powerpoint.slideshow.macroenabled.12";
    case ".mpp": return ($name) ? "Microsoft Project" : "application/vnd.ms-project";
    case ".pub": return ($name) ? "Microsoft Publisher" : "application/x-mspublisher";
    case ".scd": return ($name) ? "Microsoft Schedule+" : "application/x-msschedule";
    case ".xap": return ($name) ? "Microsoft Silverlight" : "application/x-silverlight-app";
    case ".stl": return ($name) ? "Microsoft Trust UI Provider - Certificate Trust Link" : "application/vnd.ms-pki.stl";
    case ".cat": return ($name) ? "Microsoft Trust UI Provider - Security Catalog" : "application/vnd.ms-pki.seccat";
    case ".vsd": return ($name) ? "Microsoft Visio" : "application/vnd.visio";
    case ".wm": return ($name) ? "Microsoft Windows Media" : "video/x-ms-wm";
    case ".wma": return ($name) ? "Microsoft Windows Media Audio" : "audio/x-ms-wma";
    case ".wax": return ($name) ? "Microsoft Windows Media Audio Redirector" : "audio/x-ms-wax";
    case ".wmx": return ($name) ? "Microsoft Windows Media Audio/Video Playlist" : "video/x-ms-wmx";
    case ".wmd": return ($name) ? "Microsoft Windows Media Player Download Package" : "application/x-ms-wmd";
    case ".wpl": return ($name) ? "Microsoft Windows Media Player Playlist" : "application/vnd.ms-wpl";
    case ".wmz": return ($name) ? "Microsoft Windows Media Player Skin Package" : "application/x-ms-wmz";
    case ".wmv": return ($name) ? "Microsoft Windows Media Video" : "video/x-ms-wmv";
    case ".wvx": return ($name) ? "Microsoft Windows Media Video Playlist" : "video/x-ms-wvx";
    case ".wmf": return ($name) ? "Microsoft Windows Metafile" : "application/x-msmetafile";
    case ".trm": return ($name) ? "Microsoft Windows Terminal Services" : "application/x-msterminal";
    case ".doc": return ($name) ? "Microsoft Word" : "application/msword";
    case ".wri": return ($name) ? "Microsoft Wordpad" : "application/x-mswrite";
    case ".wps": return ($name) ? "Microsoft Works" : "application/vnd.ms-works";
    case ".xbap": return ($name) ? "Microsoft XAML Browser Application" : "application/x-ms-xbap";
    case ".xps": return ($name) ? "Microsoft XML Paper Specification" : "application/vnd.ms-xpsdocument";
    case ".mid": return ($name) ? "MIDI - Musical Instrument Digital Interface" : "audio/midi";
    case ".mpy": return ($name) ? "MiniPay" : "application/vnd.ibm.minipay";
    case ".afp": return ($name) ? "MO:DCA-P" : "application/vnd.ibm.modcap";
    case ".rms": return ($name) ? "Mobile Information Device Profile" : "application/vnd.jcp.javame.midlet-rms";
    case ".tmo": return ($name) ? "MobileTV" : "application/vnd.tmobile-livetv";
    case ".prc": return ($name) ? "Mobipocket" : "application/x-mobipocket-ebook";
    case ".mbk": return ($name) ? "Mobius Management Systems - Basket file" : "application/vnd.mobius.mbk";
    case ".dis": return ($name) ? "Mobius Management Systems - Distribution Database" : "application/vnd.mobius.dis";
    case ".plc": return ($name) ? "Mobius Management Systems - Policy Definition Language File" : "application/vnd.mobius.plc";
    case ".mqy": return ($name) ? "Mobius Management Systems - Query File" : "application/vnd.mobius.mqy";
    case ".msl": return ($name) ? "Mobius Management Systems - Script Language" : "application/vnd.mobius.msl";
    case ".txf": return ($name) ? "Mobius Management Systems - Topic Index File" : "application/vnd.mobius.txf";
    case ".daf": return ($name) ? "Mobius Management Systems - UniversalArchive" : "application/vnd.mobius.daf";
    case ".fly": return ($name) ? "mod_fly / fly.cgi" : "text/vnd.fly";
    case ".mpc": return ($name) ? "Mophun Certificate" : "application/vnd.mophun.certificate";
    case ".mpn": return ($name) ? "Mophun VM" : "application/vnd.mophun.application";
    case ".mj2": return ($name) ? "Motion JPEG 2000" : "video/mj2";
    case ".mpga": return ($name) ? "MPEG Audio" : "audio/mpeg";
    case ".mxu": return ($name) ? "MPEG Url" : "video/vnd.mpegurl";
    case ".mpeg": return ($name) ? "MPEG Video" : "video/mpeg";
    case ".m21": return ($name) ? "MPEG-21" : "application/mp21";
    case ".mp4a": return ($name) ? "MPEG-4 Audio" : "audio/mp4";
    case ".mp4": return ($name) ? "MPEG-4 Video" : "video/mp4";
    /* case ".mp4": return ($name) ? "MPEG4" : "application/mp4"; */
    case ".m3u8": return ($name) ? "Multimedia Playlist Unicode" : "application/vnd.apple.mpegurl";
    case ".mus": return ($name) ? "MUsical Score Interpreted Code Invented for the ASCII designation of Notation" : "application/vnd.musician";
    case ".msty": return ($name) ? "Muvee Automatic Video Editing" : "application/vnd.muvee.style";
    case ".mxml": return ($name) ? "MXML" : "application/xv+xml";
    case ".ngdat": return ($name) ? "N-Gage Game Data" : "application/vnd.nokia.n-gage.data";
    case ".n-gage": return ($name) ? "N-Gage Game Installer" : "application/vnd.nokia.n-gage.symbian.install";
    case ".ncx": return ($name) ? "Navigation Control file for XML (for ePub)" : "application/x-dtbncx+xml";
    case ".nc": return ($name) ? "Network Common Data Form (NetCDF)" : "application/x-netcdf";
    case ".nlu": return ($name) ? "neuroLanguage" : "application/vnd.neurolanguage.nlu";
    case ".dna": return ($name) ? "New Moon Liftoff/DNA" : "application/vnd.dna";
    case ".nnd": return ($name) ? "NobleNet Directory" : "application/vnd.noblenet-directory";
    case ".nns": return ($name) ? "NobleNet Sealer" : "application/vnd.noblenet-sealer";
    case ".nnw": return ($name) ? "NobleNet Web" : "application/vnd.noblenet-web";
    case ".rpst": return ($name) ? "Nokia Radio Application - Preset" : "application/vnd.nokia.radio-preset";
    case ".rpss": return ($name) ? "Nokia Radio Application - Preset" : "application/vnd.nokia.radio-presets";
    case ".n3": return ($name) ? "Notation3" : "text/n3";
    case ".edm": return ($name) ? "Novadigm's RADIA and EDM products" : "application/vnd.novadigm.edm";
    case ".edx": return ($name) ? "Novadigm's RADIA and EDM products" : "application/vnd.novadigm.edx";
    case ".ext": return ($name) ? "Novadigm's RADIA and EDM products" : "application/vnd.novadigm.ext";
    case ".gph": return ($name) ? "NpGraphIt" : "application/vnd.flographit";
    case ".ecelp4800": return ($name) ? "Nuera ECELP 4800" : "audio/vnd.nuera.ecelp4800";
    case ".ecelp7470": return ($name) ? "Nuera ECELP 7470" : "audio/vnd.nuera.ecelp7470";
    case ".ecelp9600": return ($name) ? "Nuera ECELP 9600" : "audio/vnd.nuera.ecelp9600";
    case ".oda": return ($name) ? "Office Document Architecture" : "application/oda";
    case ".ogx": return ($name) ? "Ogg" : "application/ogg";
    case ".oga": return ($name) ? "Ogg Audio" : "audio/ogg";
    case ".ogv": return ($name) ? "Ogg Video" : "video/ogg";
    case ".dd2": return ($name) ? "OMA Download Agents" : "application/vnd.oma.dd2+xml";
    case ".oth": return ($name) ? "Open Document Text Web" : "application/vnd.oasis.opendocument.text-web";
    case ".opf": return ($name) ? "Open eBook Publication Structure" : "application/oebps-package+xml";
    case ".qbo": return ($name) ? "Open Financial Exchange" : "application/vnd.intu.qbo";
    case ".oxt": return ($name) ? "Open Office Extension" : "application/vnd.openofficeorg.extension";
    case ".osf": return ($name) ? "Open Score Format" : "application/vnd.yamaha.openscoreformat";
    case ".weba": return ($name) ? "Open Web Media Project - Audio" : "audio/webm";
    case ".webm": return ($name) ? "Open Web Media Project - Video" : "video/webm";
    case ".odc": return ($name) ? "OpenDocument Chart" : "application/vnd.oasis.opendocument.chart";
    case ".otc": return ($name) ? "OpenDocument Chart Template" : "application/vnd.oasis.opendocument.chart-template";
    case ".odb": return ($name) ? "OpenDocument Database" : "application/vnd.oasis.opendocument.database";
    case ".odf": return ($name) ? "OpenDocument Formula" : "application/vnd.oasis.opendocument.formula";
    case ".odft": return ($name) ? "OpenDocument Formula Template" : "application/vnd.oasis.opendocument.formula-template";
    case ".odg": return ($name) ? "OpenDocument Graphics" : "application/vnd.oasis.opendocument.graphics";
    case ".otg": return ($name) ? "OpenDocument Graphics Template" : "application/vnd.oasis.opendocument.graphics-template";
    case ".odi": return ($name) ? "OpenDocument Image" : "application/vnd.oasis.opendocument.image";
    case ".oti": return ($name) ? "OpenDocument Image Template" : "application/vnd.oasis.opendocument.image-template";
    case ".odp": return ($name) ? "OpenDocument Presentation" : "application/vnd.oasis.opendocument.presentation";
    case ".otp": return ($name) ? "OpenDocument Presentation Template" : "application/vnd.oasis.opendocument.presentation-template";
    case ".ods": return ($name) ? "OpenDocument Spreadsheet" : "application/vnd.oasis.opendocument.spreadsheet";
    case ".ots": return ($name) ? "OpenDocument Spreadsheet Template" : "application/vnd.oasis.opendocument.spreadsheet-template";
    case ".odt": return ($name) ? "OpenDocument Text" : "application/vnd.oasis.opendocument.text";
    case ".odm": return ($name) ? "OpenDocument Text Master" : "application/vnd.oasis.opendocument.text-master";
    case ".ott": return ($name) ? "OpenDocument Text Template" : "application/vnd.oasis.opendocument.text-template";
    case ".ktx": return ($name) ? "OpenGL Textures (KTX)" : "image/ktx";
    case ".sxc": return ($name) ? "OpenOffice - Calc (Spreadsheet)" : "application/vnd.sun.xml.calc";
    case ".stc": return ($name) ? "OpenOffice - Calc Template (Spreadsheet)" : "application/vnd.sun.xml.calc.template";
    case ".sxd": return ($name) ? "OpenOffice - Draw (Graphics)" : "application/vnd.sun.xml.draw";
    case ".std": return ($name) ? "OpenOffice - Draw Template (Graphics)" : "application/vnd.sun.xml.draw.template";
    case ".sxi": return ($name) ? "OpenOffice - Impress (Presentation)" : "application/vnd.sun.xml.impress";
    case ".sti": return ($name) ? "OpenOffice - Impress Template (Presentation)" : "application/vnd.sun.xml.impress.template";
    case ".sxm": return ($name) ? "OpenOffice - Math (Formula)" : "application/vnd.sun.xml.math";
    case ".sxw": return ($name) ? "OpenOffice - Writer (Text - HTML)" : "application/vnd.sun.xml.writer";
    case ".sxg": return ($name) ? "OpenOffice - Writer (Text - HTML)" : "application/vnd.sun.xml.writer.global";
    case ".stw": return ($name) ? "OpenOffice - Writer Template (Text - HTML)" : "application/vnd.sun.xml.writer.template";
    case ".otf": return ($name) ? "OpenType Font File" : "application/x-font-otf";
    case ".osfpvg": return ($name) ? "OSFPVG" : "application/vnd.yamaha.openscoreformat.osfpvg+xml";
    case ".dp": return ($name) ? "OSGi Deployment Package" : "application/vnd.osgi.dp";
    case ".pdb": return ($name) ? "PalmOS Data" : "application/vnd.palm";
    case ".p": return ($name) ? "Pascal Source File" : "text/x-pascal";
    case ".paw": return ($name) ? "PawaaFILE" : "application/vnd.pawaafile";
    case ".pclxl": return ($name) ? "PCL 6 Enhanced (Formely PCL XL)" : "application/vnd.hp-pclxl";
    case ".efif": return ($name) ? "Pcsel eFIF File" : "application/vnd.picsel";
    case ".pcx": return ($name) ? "PCX Image" : "image/x-pcx";
    case ".psd": return ($name) ? "Photoshop Document" : "image/vnd.adobe.photoshop";
    case ".prf": return ($name) ? "PICSRules" : "application/pics-rules";
    case ".pic": return ($name) ? "PICT Image" : "image/x-pict";
    case ".chat": return ($name) ? "pIRCh" : "application/x-chat";
    case ".p10": return ($name) ? "PKCS #10 - Certification Request Standard" : "application/pkcs10";
    case ".p12": return ($name) ? "PKCS #12 - Personal Information Exchange Syntax Standard" : "application/x-pkcs12";
    case ".p7m": return ($name) ? "PKCS #7 - Cryptographic Message Syntax Standard" : "application/pkcs7-mime";
    case ".p7s": return ($name) ? "PKCS #7 - Cryptographic Message Syntax Standard" : "application/pkcs7-signature";
    case ".p7r": return ($name) ? "PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)" : "application/x-pkcs7-certreqresp";
    case ".p7b": return ($name) ? "PKCS #7 - Cryptographic Message Syntax Standard (Certificates)" : "application/x-pkcs7-certificates";
    case ".p8": return ($name) ? "PKCS #8 - Private-Key Information Syntax Standard" : "application/pkcs8";
    case ".plf": return ($name) ? "PocketLearn Viewers" : "application/vnd.pocketlearn";
    case ".pnm": return ($name) ? "Portable Anymap Image" : "image/x-portable-anymap";
    case ".pbm": return ($name) ? "Portable Bitmap Format" : "image/x-portable-bitmap";
    case ".pcf": return ($name) ? "Portable Compiled Format" : "application/x-font-pcf";
    case ".pfr": return ($name) ? "Portable Font Resource" : "application/font-tdpfr";
    case ".pgn": return ($name) ? "Portable Game Notation (Chess Games)" : "application/x-chess-pgn";
    case ".pgm": return ($name) ? "Portable Graymap Format" : "image/x-portable-graymap";
    case ".png": return ($name) ? "Portable Network Graphics (PNG)" : "image/png";
    case ".ppm": return ($name) ? "Portable Pixmap Format" : "image/x-portable-pixmap";
    case ".pskcxml": return ($name) ? "Portable Symmetric Key Container" : "application/pskc+xml";
    case ".pml": return ($name) ? "PosML" : "application/vnd.ctc-posml";
    case ".ai": return ($name) ? "PostScript" : "application/postscript";
    case ".pfa": return ($name) ? "PostScript Fonts" : "application/x-font-type1";
    case ".pbd": return ($name) ? "PowerBuilder" : "application/vnd.powerbuilder6";
    case "": return ($name) ? "Pretty Good Privacy" : "application/pgp-encrypted";
    case ".pgp": return ($name) ? "Pretty Good Privacy - Signature" : "application/pgp-signature";
    case ".box": return ($name) ? "Preview Systems ZipLock/VBox" : "application/vnd.previewsystems.box";
    case ".ptid": return ($name) ? "Princeton Video Image" : "application/vnd.pvi.ptid1";
    case ".pls": return ($name) ? "Pronunciation Lexicon Specification" : "application/pls+xml";
    case ".str": return ($name) ? "Proprietary P&G Standard Reporting System" : "application/vnd.pg.format";
    case ".ei6": return ($name) ? "Proprietary P&G Standard Reporting System" : "application/vnd.pg.osasli";
    case ".dsc": return ($name) ? "PRS Lines Tag" : "text/prs.lines.tag";
    case ".psf": return ($name) ? "PSF Fonts" : "application/x-font-linux-psf";
    case ".qps": return ($name) ? "PubliShare Objects" : "application/vnd.publishare-delta-tree";
    case ".wg": return ($name) ? "Qualcomm's Plaza Mobile Internet" : "application/vnd.pmi.widget";
    case ".qxd": return ($name) ? "QuarkXpress" : "application/vnd.quark.quarkxpress";
    case ".esf": return ($name) ? "QUASS Stream Player" : "application/vnd.epson.esf";
    case ".msf": return ($name) ? "QUASS Stream Player" : "application/vnd.epson.msf";
    case ".ssf": return ($name) ? "QUASS Stream Player" : "application/vnd.epson.ssf";
    case ".qam": return ($name) ? "QuickAnime Player" : "application/vnd.epson.quickanime";
    case ".qfx": return ($name) ? "Quicken" : "application/vnd.intu.qfx";
    case ".qt": return ($name) ? "Quicktime Video" : "video/quicktime";
    case ".rar": return ($name) ? "RAR Archive" : "application/x-rar-compressed";
    case ".ram": return ($name) ? "Real Audio Sound" : "audio/x-pn-realaudio";
    case ".rmp": return ($name) ? "Real Audio Sound" : "audio/x-pn-realaudio-plugin";
    case ".rsd": return ($name) ? "Really Simple Discovery" : "application/rsd+xml";
    case ".rm": return ($name) ? "RealMedia" : "application/vnd.rn-realmedia";
    case ".bed": return ($name) ? "RealVNC" : "application/vnd.realvnc.bed";
    case ".mxl": return ($name) ? "Recordare Applications" : "application/vnd.recordare.musicxml";
    case ".musicxml": return ($name) ? "Recordare Applications" : "application/vnd.recordare.musicxml+xml";
    case ".rnc": return ($name) ? "Relax NG Compact Syntax" : "application/relax-ng-compact-syntax";
    case ".rdz": return ($name) ? "RemoteDocs R-Viewer" : "application/vnd.data-vision.rdz";
    case ".rdf": return ($name) ? "Resource Description Framework" : "application/rdf+xml";
    case ".rp9": return ($name) ? "RetroPlatform Player" : "application/vnd.cloanto.rp9";
    case ".jisp": return ($name) ? "RhymBox" : "application/vnd.jisp";
    case ".rtf": return ($name) ? "Rich Text Format" : "application/rtf";
    case ".rtx": return ($name) ? "Rich Text Format (RTF)" : "text/richtext";
    case ".link66": return ($name) ? "ROUTE 66 Location Based Services" : "application/vnd.route66.link66+xml";
    case ".rss, .xml": return ($name) ? "RSS - Really Simple Syndication" : "application/rss+xml";
    case ".shf": return ($name) ? "S Hexdump Format" : "application/shf+xml";
    case ".st": return ($name) ? "SailingTracker" : "application/vnd.sailingtracker.track";
    case ".svg": return ($name) ? "Scalable Vector Graphics (SVG)" : "image/svg+xml";
    case ".sus": return ($name) ? "ScheduleUs" : "application/vnd.sus-calendar";
    case ".sru": return ($name) ? "Search/Retrieve via URL Response Format" : "application/sru+xml";
    case ".setpay": return ($name) ? "Secure Electronic Transaction - Payment" : "application/set-payment-initiation";
    case ".setreg": return ($name) ? "Secure Electronic Transaction - Registration" : "application/set-registration-initiation";
    case ".sema": return ($name) ? "Secured eMail" : "application/vnd.sema";
    case ".semd": return ($name) ? "Secured eMail" : "application/vnd.semd";
    case ".semf": return ($name) ? "Secured eMail" : "application/vnd.semf";
    case ".see": return ($name) ? "SeeMail" : "application/vnd.seemail";
    case ".snf": return ($name) ? "Server Normal Format" : "application/x-font-snf";
    case ".spq": return ($name) ? "Server-Based Certificate Validation Protocol - Validation Policies - Request" : "application/scvp-vp-request";
    case ".spp": return ($name) ? "Server-Based Certificate Validation Protocol - Validation Policies - Response" : "application/scvp-vp-response";
    case ".scq": return ($name) ? "Server-Based Certificate Validation Protocol - Validation Request" : "application/scvp-cv-request";
    case ".scs": return ($name) ? "Server-Based Certificate Validation Protocol - Validation Response" : "application/scvp-cv-response";
    case ".sdp": return ($name) ? "Session Description Protocol" : "application/sdp";
    case ".etx": return ($name) ? "Setext" : "text/x-setext";
    case ".movie": return ($name) ? "SGI Movie" : "video/x-sgi-movie";
    case ".ifm": return ($name) ? "Shana Informed Filler" : "application/vnd.shana.informed.formdata";
    case ".itp": return ($name) ? "Shana Informed Filler" : "application/vnd.shana.informed.formtemplate";
    case ".iif": return ($name) ? "Shana Informed Filler" : "application/vnd.shana.informed.interchange";
    case ".ipk": return ($name) ? "Shana Informed Filler" : "application/vnd.shana.informed.package";
    case ".tfi": return ($name) ? "Sharing Transaction Fraud Data" : "application/thraud+xml";
    case ".shar": return ($name) ? "Shell Archive" : "application/x-shar";
    case ".rgb": return ($name) ? "Silicon Graphics RGB Bitmap" : "image/x-rgb";
    case ".slt": return ($name) ? "SimpleAnimeLite Player" : "application/vnd.epson.salt";
    case ".aso": return ($name) ? "Simply Accounting" : "application/vnd.accpac.simply.aso";
    case ".imp": return ($name) ? "Simply Accounting - Data Import" : "application/vnd.accpac.simply.imp";
    case ".twd": return ($name) ? "SimTech MindMapper" : "application/vnd.simtech-mindmapper";
    case ".csp": return ($name) ? "Sixth Floor Media - CommonSpace" : "application/vnd.commonspace";
    case ".saf": return ($name) ? "SMAF Audio" : "application/vnd.yamaha.smaf-audio";
    case ".mmf": return ($name) ? "SMAF File" : "application/vnd.smaf";
    case ".spf": return ($name) ? "SMAF Phrase" : "application/vnd.yamaha.smaf-phrase";
    case ".teacher": return ($name) ? "SMART Technologies Apps" : "application/vnd.smart.teacher";
    case ".svd": return ($name) ? "SourceView Document" : "application/vnd.svd";
    case ".rq": return ($name) ? "SPARQL - Query" : "application/sparql-query";
    case ".srx": return ($name) ? "SPARQL - Results" : "application/sparql-results+xml";
    case ".gram": return ($name) ? "Speech Recognition Grammar Specification" : "application/srgs";
    case ".grxml": return ($name) ? "Speech Recognition Grammar Specification - XML" : "application/srgs+xml";
    case ".ssml": return ($name) ? "Speech Synthesis Markup Language" : "application/ssml+xml";
    case ".skp": return ($name) ? "SSEYO Koan Play File" : "application/vnd.koan";
    case ".sgml": return ($name) ? "Standard Generalized Markup Language (SGML)" : "text/sgml";
    case ".sdc": return ($name) ? "StarOffice - Calc" : "application/vnd.stardivision.calc";
    case ".sda": return ($name) ? "StarOffice - Draw" : "application/vnd.stardivision.draw";
    case ".sdd": return ($name) ? "StarOffice - Impress" : "application/vnd.stardivision.impress";
    case ".smf": return ($name) ? "StarOffice - Math" : "application/vnd.stardivision.math";
    case ".sdw": return ($name) ? "StarOffice - Writer" : "application/vnd.stardivision.writer";
    case ".sgl": return ($name) ? "StarOffice - Writer (Global)" : "application/vnd.stardivision.writer-global";
    case ".sm": return ($name) ? "StepMania" : "application/vnd.stepmania.stepchart";
    case ".sit": return ($name) ? "Stuffit Archive" : "application/x-stuffit";
    case ".sitx": return ($name) ? "Stuffit Archive" : "application/x-stuffitx";
    case ".sdkm": return ($name) ? "SudokuMagic" : "application/vnd.solent.sdkm+xml";
    case ".xo": return ($name) ? "Sugar Linux Application Bundle" : "application/vnd.olpc-sugar";
    case ".au": return ($name) ? "Sun Audio - Au file format" : "audio/basic";
    case ".wqd": return ($name) ? "SundaHus WQ" : "application/vnd.wqd";
    case ".sis": return ($name) ? "Symbian Install Package" : "application/vnd.symbian.install";
    case ".smi": return ($name) ? "Synchronized Multimedia Integration Language" : "application/smil+xml";
    case ".xsm": return ($name) ? "SyncML" : "application/vnd.syncml+xml";
    case ".bdm": return ($name) ? "SyncML - Device Management" : "application/vnd.syncml.dm+wbxml";
    case ".xdm": return ($name) ? "SyncML - Device Management" : "application/vnd.syncml.dm+xml";
    case ".sv4cpio": return ($name) ? "System V Release 4 CPIO Archive" : "application/x-sv4cpio";
    case ".sv4crc": return ($name) ? "System V Release 4 CPIO Checksum Data" : "application/x-sv4crc";
    case ".sbml": return ($name) ? "Systems Biology Markup Language" : "application/sbml+xml";
    case ".tsv": return ($name) ? "Tab Seperated Values" : "text/tab-separated-values";
    case ".tiff": return ($name) ? "Tagged Image File Format" : "image/tiff";
    case ".tao": return ($name) ? "Tao Intent" : "application/vnd.tao.intent-module-archive";
    case ".tar": return ($name) ? "Tar File (Tape Archive)" : "application/x-tar";
    case ".tcl": return ($name) ? "Tcl Script" : "application/x-tcl";
    case ".tex": return ($name) ? "TeX" : "application/x-tex";
    case ".tfm": return ($name) ? "TeX Font Metric" : "application/x-tex-tfm";
    case ".tei": return ($name) ? "Text Encoding and Interchange" : "application/tei+xml";
    case ".txt": return ($name) ? "Text File" : "text/plain";
    case ".dxp": return ($name) ? "TIBCO Spotfire" : "application/vnd.spotfire.dxp";
    case ".sfs": return ($name) ? "TIBCO Spotfire" : "application/vnd.spotfire.sfs";
    case ".tsd": return ($name) ? "Time Stamped Data Envelope" : "application/timestamped-data";
    case ".tpt": return ($name) ? "TRI Systems Config" : "application/vnd.trid.tpt";
    case ".mxs": return ($name) ? "Triscape Map Explorer" : "application/vnd.triscape.mxs";
    case ".t": return ($name) ? "troff" : "text/troff";
    case ".tra": return ($name) ? "True BASIC" : "application/vnd.trueapp";
    case ".ttf": return ($name) ? "TrueType Font" : "application/x-font-ttf";
    case ".ttl": return ($name) ? "Turtle (Terse RDF Triple Language)" : "text/turtle";
    case ".umj": return ($name) ? "UMAJIN" : "application/vnd.umajin";
    case ".uoml": return ($name) ? "Unique Object Markup Language" : "application/vnd.uoml+xml";
    case ".unityweb": return ($name) ? "Unity 3d" : "application/vnd.unity";
    case ".ufd": return ($name) ? "Universal Forms Description Language" : "application/vnd.ufdl";
    case ".uri": return ($name) ? "URI Resolution Services" : "text/uri-list";
    case ".utz": return ($name) ? "User Interface Quartz - Theme (Symbian)" : "application/vnd.uiq.theme";
    case ".ustar": return ($name) ? "Ustar (Uniform Standard Tape Archive)" : "application/x-ustar";
    case ".uu": return ($name) ? "UUEncode" : "text/x-uuencode";
    case ".vcs": return ($name) ? "vCalendar" : "text/x-vcalendar";
    case ".vcf": return ($name) ? "vCard" : "text/x-vcard";
    case ".vcd": return ($name) ? "Video CD" : "application/x-cdlink";
    case ".vsf": return ($name) ? "Viewport+" : "application/vnd.vsf";
    case ".wrl": return ($name) ? "Virtual Reality Modeling Language" : "model/vrml";
    case ".vcx": return ($name) ? "VirtualCatalog" : "application/vnd.vcx";
    case ".mts": return ($name) ? "Virtue MTS" : "model/vnd.mts";
    case ".vtu": return ($name) ? "Virtue VTU" : "model/vnd.vtu";
    case ".vis": return ($name) ? "Visionary" : "application/vnd.visionary";
    case ".viv": return ($name) ? "Vivo" : "video/vnd.vivo";
    case ".ccxml": return ($name) ? "Voice Browser Call Control" : "application/ccxml+xml,";
    case ".vxml": return ($name) ? "VoiceXML" : "application/voicexml+xml";
    case ".src": return ($name) ? "WAIS Source" : "application/x-wais-source";
    case ".wbxml": return ($name) ? "WAP Binary XML (WBXML)" : "application/vnd.wap.wbxml";
    case ".wbmp": return ($name) ? "WAP Bitamp (WBMP)" : "image/vnd.wap.wbmp";
    case ".wav": return ($name) ? "Waveform Audio File Format (WAV)" : "audio/x-wav";
    case ".davmount": return ($name) ? "Web Distributed Authoring and Versioning" : "application/davmount+xml";
    case ".woff": return ($name) ? "Web Open Font Format" : "application/x-font-woff";
    case ".wspolicy": return ($name) ? "Web Services Policy" : "application/wspolicy+xml";
    case ".webp": return ($name) ? "WebP Image" : "image/webp";
    case ".wtb": return ($name) ? "WebTurbo" : "application/vnd.webturbo";
    case ".wgt": return ($name) ? "Widget Packaging and XML Configuration" : "application/widget";
    case ".hlp": return ($name) ? "WinHelp" : "application/winhlp";
    case ".wml": return ($name) ? "Wireless Markup Language (WML)" : "text/vnd.wap.wml";
    case ".wmls": return ($name) ? "Wireless Markup Language Script (WMLScript)" : "text/vnd.wap.wmlscript";
    case ".wmlsc": return ($name) ? "WMLScript" : "application/vnd.wap.wmlscriptc";
    case ".wpd": return ($name) ? "Wordperfect" : "application/vnd.wordperfect";
    case ".stf": return ($name) ? "Worldtalk" : "application/vnd.wt.stf";
    case ".wsdl": return ($name) ? "WSDL - Web Services Description Language" : "application/wsdl+xml";
    case ".xbm": return ($name) ? "X BitMap" : "image/x-xbitmap";
    case ".xpm": return ($name) ? "X PixMap" : "image/x-xpixmap";
    case ".xwd": return ($name) ? "X Window Dump" : "image/x-xwindowdump";
    case ".der": return ($name) ? "X.509 Certificate" : "application/x-x509-ca-cert";
    case ".fig": return ($name) ? "Xfig" : "application/x-xfig";
    case ".xhtml": return ($name) ? "XHTML - The Extensible HyperText Markup Language" : "application/xhtml+xml";
    case ".xml": return ($name) ? "XML - Extensible Markup Language" : "application/xml";
    case ".xdf": return ($name) ? "XML Configuration Access Protocol - XCAP Diff" : "application/xcap-diff+xml";
    case ".xenc": return ($name) ? "XML Encryption Syntax and Processing" : "application/xenc+xml";
    case ".xer": return ($name) ? "XML Patch Framework" : "application/patch-ops-error+xml";
    case ".rl": return ($name) ? "XML Resource Lists" : "application/resource-lists+xml";
    case ".rs": return ($name) ? "XML Resource Lists" : "application/rls-services+xml";
    case ".rld": return ($name) ? "XML Resource Lists Diff" : "application/resource-lists-diff+xml";
    case ".xslt": return ($name) ? "XML Transformations" : "application/xslt+xml";
    case ".xop": return ($name) ? "XML-Binary Optimized Packaging" : "application/xop+xml";
    case ".xpi": return ($name) ? "XPInstall - Mozilla" : "application/x-xpinstall";
    case ".xspf": return ($name) ? "XSPF - XML Shareable Playlist Format" : "application/xspf+xml";
    case ".xul": return ($name) ? "XUL - XML User Interface Language" : "application/vnd.mozilla.xul+xml";
    case ".xyz": return ($name) ? "XYZ File Format" : "chemical/x-xyz";
    case ".yaml": return ($name) ? "YAML Ain't Markup Language / Yet Another Markup Language" : "text/yaml";
    case ".yang": return ($name) ? "YANG Data Modeling Language" : "application/yang";
    case ".yin": return ($name) ? "YIN (YANG - XML)" : "application/yin+xml";
    case ".zir": return ($name) ? "Z.U.L. Geometry" : "application/vnd.zul";
    case ".zip": return ($name) ? "Zip Archive" : "application/zip";
    case ".zmm": return ($name) ? "ZVUE Media Manager" : "application/vnd.handheld-entertainment+xml";
    case ".zaz": return ($name) ? "Zzazz Deck" : "application/vnd.zzazz.deck+xml";
    }
    return "application/octet-stream";
}
?>